import type { TeckelNodeType, NodeCategory } from "@/types/pipeline";
import {
  Database,
  Download,
  Columns3,
  Filter,
  GitMerge,
  Group,
  ArrowUpDown,
  Code,
  AppWindow,
  Combine,
  CircleDot,
  Split,
  Plus,
  Minus,
  Replace,
  CaseSensitive,
  Fingerprint,
  Hash,
  Percent,
  RotateCcw,
  RotateCw,
  Shrink,
  Expand,
  Layers,
  GitBranch,
  SplitSquareVertical,
  BarChart3,
  Box,
  Clock,
  Globe,
  Shield,
  AlertTriangle,
  Puzzle,
  type LucideIcon,
} from "lucide-react";

export interface NodeDefinition {
  type: TeckelNodeType;
  label: string;
  category: NodeCategory;
  color: string;
  icon: LucideIcon;
  defaultConfig: Record<string, unknown>;
}

export const NODE_REGISTRY: Record<TeckelNodeType, NodeDefinition> = {
  input: {
    type: "input",
    label: "Input",
    category: "sources",
    color: "#10b981",
    icon: Database,
    defaultConfig: { format: "parquet", path: "", options: {}, description: "", tags: [], meta: {}, owner: "" },
  },
  output: {
    type: "output",
    label: "Output",
    category: "sinks",
    color: "#f43f5e",
    icon: Download,
    defaultConfig: { format: "parquet", mode: "overwrite", path: "", partitionBy: [], options: {}, description: "", tags: [], meta: {}, freshness: "", maturity: "" },
  },
  select: {
    type: "select",
    label: "Select",
    category: "columns",
    color: "#3b82f6",
    icon: Columns3,
    defaultConfig: { columns: [] },
  },
  where: {
    type: "where",
    label: "Where",
    category: "filtering",
    color: "#f59e0b",
    icon: Filter,
    defaultConfig: { filter: "" },
  },
  join: {
    type: "join",
    label: "Join",
    category: "joins-sets",
    color: "#8b5cf6",
    icon: GitMerge,
    defaultConfig: { joinType: "inner", on: "" },
  },
  groupBy: {
    type: "groupBy",
    label: "Group By",
    category: "aggregation",
    color: "#06b6d4",
    icon: Group,
    defaultConfig: { by: [], agg: [] },
  },
  orderBy: {
    type: "orderBy",
    label: "Order By",
    category: "aggregation",
    color: "#f97316",
    icon: ArrowUpDown,
    defaultConfig: { columns: [] },
  },
  sql: {
    type: "sql",
    label: "SQL",
    category: "advanced",
    color: "#d946ef",
    icon: Code,
    defaultConfig: { query: "", views: [] },
  },
  window: {
    type: "window",
    label: "Window",
    category: "aggregation",
    color: "#14b8a6",
    icon: AppWindow,
    defaultConfig: {
      partitionBy: [],
      orderBy: [],
      frame: { type: "range", start: "unbounded preceding", end: "current row" },
      functions: [],
    },
  },
  union: {
    type: "union",
    label: "Union",
    category: "joins-sets",
    color: "#84cc16",
    icon: Combine,
    defaultConfig: { sources: [], all: true },
  },
  intersect: {
    type: "intersect",
    label: "Intersect",
    category: "joins-sets",
    color: "#0ea5e9",
    icon: CircleDot,
    defaultConfig: { sources: [], all: false },
  },
  except: {
    type: "except",
    label: "Except",
    category: "joins-sets",
    color: "#ef4444",
    icon: Split,
    defaultConfig: { left: "", right: "", all: false },
  },
  addColumns: {
    type: "addColumns",
    label: "Add Columns",
    category: "columns",
    color: "#6366f1",
    icon: Plus,
    defaultConfig: { columns: [] },
  },
  dropColumns: {
    type: "dropColumns",
    label: "Drop Columns",
    category: "columns",
    color: "#ec4899",
    icon: Minus,
    defaultConfig: { columns: [] },
  },
  renameColumns: {
    type: "renameColumns",
    label: "Rename Columns",
    category: "columns",
    color: "#a855f7",
    icon: Replace,
    defaultConfig: { mappings: {} },
  },
  castColumns: {
    type: "castColumns",
    label: "Cast Columns",
    category: "columns",
    color: "#eab308",
    icon: CaseSensitive,
    defaultConfig: { columns: [] },
  },
  distinct: {
    type: "distinct",
    label: "Distinct",
    category: "filtering",
    color: "#10b981",
    icon: Fingerprint,
    defaultConfig: { columns: [] },
  },
  limit: {
    type: "limit",
    label: "Limit",
    category: "filtering",
    color: "#64748b",
    icon: Hash,
    defaultConfig: { count: 100 },
  },
  sample: {
    type: "sample",
    label: "Sample",
    category: "filtering",
    color: "#78716c",
    icon: Percent,
    defaultConfig: { fraction: 0.1, withReplacement: false, seed: null },
  },
  pivot: {
    type: "pivot",
    label: "Pivot",
    category: "reshaping",
    color: "#3b82f6",
    icon: RotateCcw,
    defaultConfig: { groupBy: [], pivotColumn: "", values: [], agg: [] },
  },
  unpivot: {
    type: "unpivot",
    label: "Unpivot",
    category: "reshaping",
    color: "#8b5cf6",
    icon: RotateCw,
    defaultConfig: { ids: [], values: [], variableColumn: "", valueColumn: "" },
  },
  repartition: {
    type: "repartition",
    label: "Repartition",
    category: "advanced",
    color: "#6b7280",
    icon: Expand,
    defaultConfig: { numPartitions: 200, columns: [] },
  },
  coalesce: {
    type: "coalesce",
    label: "Coalesce",
    category: "advanced",
    color: "#52525b",
    icon: Shrink,
    defaultConfig: { numPartitions: 1 },
  },
  flatten: {
    type: "flatten",
    label: "Flatten",
    category: "reshaping",
    color: "#0d9488",
    icon: Layers,
    defaultConfig: { separator: "_", explodeArrays: false },
  },
  conditional: {
    type: "conditional",
    label: "Conditional",
    category: "filtering",
    color: "#c026d3",
    icon: GitBranch,
    defaultConfig: { outputColumn: "", branches: [], otherwise: "" },
  },
  split: {
    type: "split",
    label: "Split",
    category: "filtering",
    color: "#e11d48",
    icon: SplitSquareVertical,
    defaultConfig: { condition: "", pass: "", fail: "" },
  },
  rollup: {
    type: "rollup",
    label: "Rollup",
    category: "aggregation",
    color: "#0891b2",
    icon: BarChart3,
    defaultConfig: { by: [], agg: [] },
  },
  cube: {
    type: "cube",
    label: "Cube",
    category: "aggregation",
    color: "#7c3aed",
    icon: Box,
    defaultConfig: { by: [], agg: [] },
  },
  scd2: {
    type: "scd2",
    label: "SCD Type 2",
    category: "advanced",
    color: "#b45309",
    icon: Clock,
    defaultConfig: {
      keyColumns: [],
      trackColumns: [],
      startDateColumn: "",
      endDateColumn: "",
      currentFlagColumn: "",
    },
  },
  enrich: {
    type: "enrich",
    label: "Enrich",
    category: "advanced",
    color: "#059669",
    icon: Globe,
    defaultConfig: {
      url: "",
      method: "GET",
      keyColumn: "",
      responseColumn: "",
      headers: {},
      onError: "null",
      timeout: 30000,
      maxRetries: 3,
    },
  },
  schemaEnforce: {
    type: "schemaEnforce",
    label: "Schema Enforce",
    category: "quality",
    color: "#2563eb",
    icon: Shield,
    defaultConfig: { mode: "strict", columns: [] },
  },
  assertion: {
    type: "assertion",
    label: "Assertion",
    category: "quality",
    color: "#dc2626",
    icon: AlertTriangle,
    defaultConfig: { checks: [], onFailure: "fail" },
  },
  custom: {
    type: "custom",
    label: "Custom",
    category: "advanced",
    color: "#9333ea",
    icon: Puzzle,
    defaultConfig: { component: "", options: {} },
  },
};

export const NODE_CATEGORIES: { key: NodeCategory; label: string; types: TeckelNodeType[] }[] = [
  { key: "sources", label: "Sources", types: ["input"] },
  { key: "sinks", label: "Sinks", types: ["output"] },
  {
    key: "columns",
    label: "Columns",
    types: ["addColumns", "castColumns", "dropColumns", "renameColumns", "select"],
  },
  {
    key: "filtering",
    label: "Filtering",
    types: ["conditional", "distinct", "limit", "sample", "split", "where"],
  },
  {
    key: "aggregation",
    label: "Aggregation & Sorting",
    types: ["cube", "groupBy", "orderBy", "rollup", "window"],
  },
  {
    key: "joins-sets",
    label: "Joins & Sets",
    types: ["except", "intersect", "join", "union"],
  },
  {
    key: "reshaping",
    label: "Reshaping",
    types: ["flatten", "pivot", "unpivot"],
  },
  {
    key: "quality",
    label: "Quality",
    types: ["assertion", "schemaEnforce"],
  },
  {
    key: "advanced",
    label: "Advanced",
    types: ["coalesce", "custom", "enrich", "repartition", "scd2", "sql"],
  },
];
