import type { TeckelNodeType, NodeCategory } from "@/types/pipeline";
import {
  Database,
  Download,
  Columns3,
  Filter,
  GitMerge,
  Group,
  ArrowUpDown,
  Code,
  AppWindow,
  Combine,
  CircleDot,
  Split,
  Plus,
  Minus,
  Replace,
  CaseSensitive,
  Fingerprint,
  Hash,
  Percent,
  RotateCcw,
  RotateCw,
  Shrink,
  Expand,
  type LucideIcon,
} from "lucide-react";

export interface NodeDefinition {
  type: TeckelNodeType;
  label: string;
  category: NodeCategory;
  color: string;
  icon: LucideIcon;
  defaultConfig: Record<string, unknown>;
}

export const NODE_REGISTRY: Record<TeckelNodeType, NodeDefinition> = {
  input: {
    type: "input",
    label: "Input",
    category: "sources",
    color: "#10b981",
    icon: Database,
    defaultConfig: { format: "parquet", path: "", options: {} },
  },
  output: {
    type: "output",
    label: "Output",
    category: "sinks",
    color: "#f43f5e",
    icon: Download,
    defaultConfig: { format: "parquet", mode: "overwrite", path: "", partitionBy: [], options: {} },
  },
  select: {
    type: "select",
    label: "Select",
    category: "transforms",
    color: "#3b82f6",
    icon: Columns3,
    defaultConfig: { columns: [] },
  },
  where: {
    type: "where",
    label: "Where",
    category: "transforms",
    color: "#f59e0b",
    icon: Filter,
    defaultConfig: { condition: "" },
  },
  join: {
    type: "join",
    label: "Join",
    category: "transforms",
    color: "#8b5cf6",
    icon: GitMerge,
    defaultConfig: { ref: "", on: "", joinType: "inner" },
  },
  groupBy: {
    type: "groupBy",
    label: "Group By",
    category: "transforms",
    color: "#06b6d4",
    icon: Group,
    defaultConfig: { columns: [], agg: [] },
  },
  orderBy: {
    type: "orderBy",
    label: "Order By",
    category: "transforms",
    color: "#f97316",
    icon: ArrowUpDown,
    defaultConfig: { columns: [] },
  },
  sql: {
    type: "sql",
    label: "SQL",
    category: "transforms",
    color: "#d946ef",
    icon: Code,
    defaultConfig: { query: "" },
  },
  window: {
    type: "window",
    label: "Window",
    category: "transforms",
    color: "#14b8a6",
    icon: AppWindow,
    defaultConfig: { partitionBy: [], orderBy: [], frame: {} },
  },
  union: {
    type: "union",
    label: "Union",
    category: "transforms",
    color: "#84cc16",
    icon: Combine,
    defaultConfig: { refs: [] },
  },
  intersect: {
    type: "intersect",
    label: "Intersect",
    category: "transforms",
    color: "#0ea5e9",
    icon: CircleDot,
    defaultConfig: { refs: [] },
  },
  except: {
    type: "except",
    label: "Except",
    category: "transforms",
    color: "#ef4444",
    icon: Split,
    defaultConfig: { refs: [] },
  },
  addColumns: {
    type: "addColumns",
    label: "Add Columns",
    category: "transforms",
    color: "#6366f1",
    icon: Plus,
    defaultConfig: { columns: [] },
  },
  dropColumns: {
    type: "dropColumns",
    label: "Drop Columns",
    category: "transforms",
    color: "#ec4899",
    icon: Minus,
    defaultConfig: { columns: [] },
  },
  renameColumns: {
    type: "renameColumns",
    label: "Rename Columns",
    category: "transforms",
    color: "#a855f7",
    icon: Replace,
    defaultConfig: { mapping: {} },
  },
  castColumns: {
    type: "castColumns",
    label: "Cast Columns",
    category: "transforms",
    color: "#eab308",
    icon: CaseSensitive,
    defaultConfig: { mapping: {} },
  },
  distinct: {
    type: "distinct",
    label: "Distinct",
    category: "transforms",
    color: "#10b981",
    icon: Fingerprint,
    defaultConfig: {},
  },
  limit: {
    type: "limit",
    label: "Limit",
    category: "transforms",
    color: "#64748b",
    icon: Hash,
    defaultConfig: { count: 100 },
  },
  sample: {
    type: "sample",
    label: "Sample",
    category: "transforms",
    color: "#78716c",
    icon: Percent,
    defaultConfig: { fraction: 0.1, seed: null },
  },
  pivot: {
    type: "pivot",
    label: "Pivot",
    category: "transforms",
    color: "#3b82f6",
    icon: RotateCcw,
    defaultConfig: { pivotColumn: "", values: [], agg: {} },
  },
  unpivot: {
    type: "unpivot",
    label: "Unpivot",
    category: "transforms",
    color: "#8b5cf6",
    icon: RotateCw,
    defaultConfig: { idColumns: [], valueColumns: [] },
  },
  repartition: {
    type: "repartition",
    label: "Repartition",
    category: "transforms",
    color: "#6b7280",
    icon: Expand,
    defaultConfig: { numPartitions: 200 },
  },
  coalesce: {
    type: "coalesce",
    label: "Coalesce",
    category: "transforms",
    color: "#52525b",
    icon: Shrink,
    defaultConfig: { numPartitions: 1 },
  },
};

export const NODE_CATEGORIES: { key: NodeCategory; label: string; types: TeckelNodeType[] }[] = [
  { key: "sources", label: "Sources", types: ["input"] },
  { key: "sinks", label: "Sinks", types: ["output"] },
  {
    key: "transforms",
    label: "Transforms",
    types: [
      "select",
      "where",
      "join",
      "groupBy",
      "orderBy",
      "sql",
      "window",
      "union",
      "intersect",
      "except",
      "addColumns",
      "dropColumns",
      "renameColumns",
      "castColumns",
      "distinct",
      "limit",
      "sample",
      "pivot",
      "unpivot",
      "repartition",
      "coalesce",
    ],
  },
];
